name: PR Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Check for Label
        run: |
          LABEL_NAME="your-label-name"
          if [[ $(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
                      | jq -r ".[].name" \
                      | grep -c "$LABEL_NAME") -eq 0 ]]; then
            echo "Label $LABEL_NAME not found on the pull request."
            exit 1
          fi