name: PR Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message in Test
        run: echo "Hello DevOps Pro"

